name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run postman tests
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

  login:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job completes before this one
    steps:
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

  run_tests:
    runs-on: ubuntu-latest
    needs: [build, login]  # Ensure that both 'build' and 'login' jobs complete before this one
    steps:
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/test Copy.json" --integration-id "149296-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint e7f2bd00-c422-4b73-baf9-20154cd17e59 --integration-id 149296
